export const data = [
  {
    icon: `<i class="far fa-edit service-card-icon"></i>`,
    title: `Diseño y comunicación`,
    list: [
      "UX / UI",
      "Diseño web",
      "Diseño interactivo",
      "Diseño editorial",
      "Diseño gráfico",
      "Branding",
      "Preproducción, producción y postproducción audiovisual",
      "Motion graphics",
      "Arte digital",
      "Fotografía",
      "Ilustraciones",
      "Comunicación digital",
      "Creación de contenido y corrección de estilo",
      "Impresiones generales",
      "VDP",
    ],
  },
  {
    icon: `<i class="far fa-file-code service-card-icon"></i>`,
    title: `Desarrollo`,
    list: [
      "Project managment",
      "Mantenimiento web",
      "Desarrollo de software a medida",
      "Desarrollo web y mobile",
      "Realidad virtual",
      "Realidad aumentada",
      "E-commerce",
      "Implementación y desarrollo ERP",
      "CRM",
      "CMS",
      "IoT",
      "Data science",
    ],
  },
  {
    icon: `<i class="fas fa-chalkboard service-card-icon"></i>`,
    title: `Capacitación y consultoría `,
    list: [
      "Project managment",
      "Data science",
      "Soluciones integrales de business intelligence",
      "Aseguramiento de la calidad",
      "Consultoría tecnológica",
      "Capacitaciones docentes",
      "Cursos de programación",
      "Talleres de tecnología creativa",
    ],
  },
  {
    icon: `<i class="fas fa-hammer service-card-icon"></i>`,
    title: `Infraestructura`,
    list: [
      "Integraciones hardware y software",
      "Cableados estructurados",
      "Administración de servidores",
      "Infraestructura como código",
    ],
  },
];

export const companyLogos = [
  "https://facttic.org.ar/fit/static/img/tech-logos/express.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/ionic.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/django.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/react.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/angular-icon.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/nodejs.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/vuejs.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/es6.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/ui5.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/feathers.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/grunt.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/vuenative.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/android-studio.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/html5.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/css3.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/bootstrap.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/sass.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/java.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/python.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/elixir.png",
  "https://facttic.org.ar/fit/static/img/tech-logos/aws.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/drupal.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/wordpress.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/shopify.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/laravel.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/symfony.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/apache.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/php.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/mysql.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/mongodb.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/mariadb.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/couchdb.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/firebird.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/postgresql.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/net.png",
  "https://facttic.org.ar/fit/static/img/tech-logos/redis.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/heroku.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/docker.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/kubernetes.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/virtualbox.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/suitecrm.png",
  "https://facttic.org.ar/fit/static/img/tech-logos/celery.png",
  "https://facttic.org.ar/fit/static/img/tech-logos/tryton.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/threejs.png",
  "https://facttic.org.ar/fit/static/img/tech-logos/processing.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/unity.svg",
  "https://facttic.org.ar/fit/static/img/tech-logos/sparkar.png",
  "https://facttic.org.ar/fit/static/img/tech-logos/arduino.svg",
];

export const cases = [
  {
    title: "Shopper Trolley",
    type: "Comercio",
    desc:
      "Desarrollo de un Mockup de una App Mobile (Android + iOS) para fidelización de clientes. A través de ella, se escanean códigos QR de productos y se obtienen premios o beneficios.",
    list: {
      cliente: "Inventor group",
      pais: "Australia",
      tecnologías: "React native",
      servicios: "Desarrollo mobile a medida",
      cooperativas: 2,
      trabajadores: 4,
    },
    logo: "./images/shopper-trolley.png",
  },
  {
    title: "Betterez",
    type: "Reservations & ticketing platform",
    desc:
      "Desarrollo desde hace más de 5 años de la aplicación web que ha crecido en decenas de microservicios, API Rest y mobile apps.",
    list: {
      cliente: "Betterez Inc",
      pais: "Canadá",
      tecnologías: "Node.js, Elixir, VueJS, MongoDB, PostgreSQL, Docker, Redis",
      servicios: "Equipo de desarrollo y manejo de recursos permanente",
      cooperativas: 7,
      trabajadores: 20,
    },
    logo: "./images/2.png",
  },
  {
    title: "Aquiles",
    type: "Facturación electrónica",
    desc:
      "Desarrollo y mantenimiento de sistema web de facturación electrónica.",
    list: {
      cliente: " Producto propio",
      pais: "Argentina",
      tecnologías: "Python / Django WebPack, JavaScript, HTML, CSS, Bootstrap",
      servicios: "Desarrollo y mantenimiento",
      cooperativas: 2,
      trabajadores: 4,
    },
    logo: "./images/3.png",
  },
];
